apiVersion: v1
kind: Service
metadata:
  name: unify-controller
  namespace: home-automation
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unify.united
spec:
  loadBalancerIP: 10.0.0.244
  ports:
    - name: device-comm
      port: 8080
      protocol: TCP
    - name: stun
      port: 3478
      protocol: UDP
    - name: default-console
      port: 8443
      protocol: TCP
    - name: secure-redirect
      port: 8843
      protocol: TCP
    - name: http-redirect
      port: 8880
      protocol: TCP
    - name: speedtest
      port: 6789
      protocol: TCP
    - name: unifi-disc
      port: 10001
      protocol: UDP
    - name: unifi-disc-l2
      port: 1900
      protocol: UDP
  selector:
    app.kubernetes.io/name: unify-controller 
  type: LoadBalancer
