apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unify-controller
  namespace: home-automation 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unify-controller 
  serviceName: unify-controller
  replicas: 1 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unify-controller 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: unify-controller
        image: linuxserver/unifi-network-application:9.0.114
        resources:
          requests:
            cpu: 150m
            memory: 1024Mi
          limits:
            cpu: 512m
            memory: 2048Mi
        ports:
          - name: device-comm
            containerPort: 8080
            protocol: TCP
          - name: stun
            containerPort: 3478
            protocol: UDP
          - name: default-console
            containerPort: 8443
            protocol: TCP
          - name: secure-redirect
            containerPort: 8843
            protocol: TCP
          - name: http-redirect
            containerPort: 8880
            protocol: TCP
          - name: speedtest
            containerPort: 6789
            protocol: TCP
          - name: unifi-disc
            containerPort: 10001
            protocol: UDP
          - name: unifi-disc-l2
            containerPort: 1900
            protocol: UDP
        volumeMounts:
          - name: data 
            mountPath: /config 
      volumes:
        - name: data
          emptyDir: {}
