apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default 
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "infra-system"
        in_cluster_config = true
      }
    }
