apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: test 
  namespace: infra-system
  annotations:
    crossplane.io/external-name: test 
spec:
  writeConnectionSecretToRef:
    namespace: infra-system 
    name: terraform-workspace-test
  forProvider:
    source: Inline
    module: |
      resource "random_pet" "realm_nickname" {}

      resource "keycloak_realm" "realm" {
        realm   = random_pet.realm_nickname.id 
      }
