apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  secretName: grafana-tls
  privateKey:
    rotationPolicy: Always
  commonName: grafana.wimandnaomishome.com
  dnsNames:
    - grafana.wimandnaomishome.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: cloudflare 
    kind: ClusterIssuer
