apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: 4546b
  labels:
    argocd.argoproj.io/instance: infra-system-cert-manager
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: 4546b
      key: ca.crt
  target:
    configMap:
      key: "trust-bundle.pem"
