apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAcETrTqnJLsCBYkufVMt0A2XFuqSVx7rbG1NjPNAKuW1101CYZ3CoNJv09wISfmDFwwkikvamL7OknTauWJivk4NfBZiNaCqbMH5LNrvOXrQXgad9NFqH9/I0tcvHnffwoloIZYFd0KRrxCN4ScErcPSrlONUlRMhjaHi68+mywM1dy/8Uix+v71fwteT1L0zlHuxjZ8Eolj0lX7fRZ78je24+f5nsSGIFHjW+r1LjIIX7KQvfpSRPzdwUqzi5qZLFoxX1U2d5k1at2lOhjt59XstesWE6gjz2wukC+1qtSORNtce5dgpv3i3dW4Q50QjbVzrfW845+quw3NeM4uMs2G30aeDPqykSsqOcyXUcSGzn1UvuyQpXNmr4xcJrWBRdkByCcaC5lpYnPMBfIJHt7kSUjLtROKplmhuFHxjJiXtO2l7rLdMwvDgZFRsGJxi7S77FJhOUEoHm+qoAjMsgVNiVorcap010S3OE6MVt9k3aYgHo5ni6H07bbh49l8L1G992dR+TMWDZbC0Oy2I34kGHb63vRT3Q9KHOK6GtN/+uu43D84vCZIG45ZFw5C03judRG0aPRLs8fZ2d8yXeBcNtzA2wUPz40CorMcWrrCLOV3we9wrLxmyULUu5RbzkAiTn5PTc0NkhdBmcvFi/mmUpJDm45MAlVtoh26FYfbu2wD2OQg4thJ8bFiL9Q7cdp4YedoGFbF59XPwokCSXqZPRNt0bJk5SpwLhe8oMN9yfMM/5Hvq3
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
