apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default 
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: infra-system
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-cert-controller
          namespace: infra-system
