apiVersion: generators.external-secrets.io/v1
kind: ClusterGenerator
metadata:
  name: password-generator
  namespace: infra-system
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 64
      digits: 10
      symbols: 10
      symbolCharacters: "-_?^#!&%@"
      noUpper: false
      allowRepeat: true 
