---
kind: Cluster
name: 4546B
talos:
  version: v1.9.2
kubernetes:
  version: 1.31.2
features:
  enableWorkloadProxy: false
patches:
  - name: kubespan
    file: patches/kubespan.yaml
  - name: data-engine
    file: patches/data-engine.yaml
systemExtensions:
  - siderolabs/iscsi-tools
  - siderolabs/util-linux-tools
---
kind: ControlPlane
machineClass:
  name: controlplane
  size: 3
patches:
  - name: scheduling
    file: patches/scheduling.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machineClass:
  name: worker
  size: unlimited
