nameOverride: keycloak-operator
namespaceOverride: infra-system

global:
  image:
    tag: ''

keycloak:
  production: true
  proxyHeaders: "xforwarded"
  proxy: edge
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 400
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 60
    successThreshold: 1
  metrics:
    enabled: true
  postgresql:
    enabled: false
  externalDatabase:
    host: keycloak-rw.infra-system.svc.cluster.local
    existingSecret: keycloak-app
    existingSecretPortKey: port
    existingSecretUserKey: user 
    existingSecretDatabaseKey: dbname
    existingSecretPasswordKey: password
  auth:
    existingSecret: keycloak-initial-admin-creds
    passwordSecretKey: password
  ingress:
    enabled: true
    hostname: keycloak.united
    path: /
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: 4546b 
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  extraVolumes:
    - name: trustbundle
      configMap:
        name: 4546b
  extraVolumeMounts:
    - name: trustbundle
      mountPath: /etc/ssl/certs/trust-bundle.pem
      subPath: trust-bundle.pem
