apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    kubernetes.io/metadata.name: linkerd 
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest   
    linkerd.io/inject: enabled
