apiVersion: v1
data:
  policy.csv: |
    p, role:image-updater, applications, get, */*, allow
    p, role:image-updater, applications, update, */*, allow
    g, image-updater, role:image-updater
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
