apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
spec:
  encryptedData:
    argocd.token: AgAhdWTgJ8apl3BSbeJFVkC9Q8rljTqAzJ1+i3i+YRG05a9GeWnXsr+cG5d8sYSjN7/ioiNunBZO4vchhTeb9dRg1Mn6PcT8A8X4i8ZL2dyhBrSNW7tfuk9NooSNE1Qd8SDTjLzDJ5tOKS0k9XpsGGm8qOZDyfbN469+oMVWcJ7h1pviRVGK4PRMVIopnVHpDzD31YNedbj8lzDk2zdWX9K+j78WwnR6baRtb66BFkoO3+xvfiVQVKQy11ZbCHpd4/F84C/quXmlm3B/le96oO5Q2DZDQMIbHzzfrCigrcszEkdu32y3g25R/hRzU177Lmp5/R2iyWbmztehf1M4s2VGbI99xGu0jgLkffvw8/d86flMo52/nL49Jatchv5IWUFenH7jyThtIejO11+rl/er9tkKIOgIwTPXGtRFoM6UWYQcVU/kJ2B1PN8G9UxV/MzV7oUwHCNPrXGeyC6VJkW7YPuN5XrRv7IJ/opbm9QYBB4KL0ES2YdsqS+G6ocfTwCNOtjf9jleibYHvn0axjuW4mnEQ22JulkkoFsk/S4oWXLDH01dxtxY4NGUvDnC5jbUQbhypkAZ5sHg0OHwe5Ophvwfo1Fi4Wv9O+vtsUXfOCAx5BU+gRHb6GlNreKfQktEe/HPpzBvcAt5kjrYXXABNhiPHdVHsd1nQoI3ulvoAg8OijvErxlp8Xz1648hQAb3JR4VAoGchVKkhBkdg8MO1LzD28N9w9OBj+AkmjtER9qfvJBHyJDR6pqsHI62c5uRBAuXUe9CqgNqr2xeCiFkEJBnNkkxCj+NB65ThoJ5FXHW+VV77tTtWbBGKbfIxcJjEo2Zheayj8EwEJXx6KT6ingYHIhNPk57Rd8ck9aAyyBJueZJn4Q9/912FGy9EOJPsIvQI/7UhKUNe+wBi1dMxscVJPLCwvbif8i08GLGrWFgtxFA6+pOSxCu9V/f1MOEBhbiLiBpJ7w21np/VY+ppq8D2J2mNgA=
  template:
    metadata:
      name: argocd-image-updater-secret
      namespace: argocd
