apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
spec:
  secretName: argocd-server-tls
  privateKey:
    rotationPolicy: Always
  commonName: argocd.wimandnaomishome.com
  dnsNames:
    - argocd.wimandnaomishome.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: cloudflare 
    kind: ClusterIssuer
