namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.9.3
  - bootstrap-app-set.yaml

patches:
  - path: argocd-cm.yaml
  - path: argocd-rbac-cm.yaml
