apiVersion: v2
name: linkerd
version: 2024.9.2
dependencies:
  - name: linkerd-crds
    version: 2024.9.2 
    repository: https://helm.linkerd.io/edge
  - name: linkerd-control-plane
    version: 2024.9.2
    repository: https://helm.linkerd.io/edge
