
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oauth2-credentials
  namespace: infra-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: argocd-oauth2-credentials
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      engineVersion: v2
      data:
        oidc.keycloak.clientId: argo-cd
        oidc.keycloak.clientSecret: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password-generator
