apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloak
metadata:
  name: keycloak
  namespace: infra-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: iam
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  secret: initial-admin-credentials
  url: http://keycloak.infra-system.svc.cluster.local
