apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secret
  namespace: infra-system
  labels:
    app.kubernetes.io/instance: infra-system-keycloak
    argocd.argoproj.io/instance: infra-system-keycloak
spec:
  refreshInterval: "0"
  target:
    name: keycloak-initial-admin-creds
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password-generator
