apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: initial-admin-credentials
  namespace: infra-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: database
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: iam
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: initial-admin-credentials
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password-generator
