---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.global.image.tag | default .Chart.AppVersion }}
  name: {{ .Values.nameOverride | default .Chart.Name }}-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.nameOverride | default .Chart.Name }}
