---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.global.image.tag | default .Chart.AppVersion }}
  name: {{ .Values.nameOverride | default .Chart.Name }}
