apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: netbird-backend
spec:
  deletionPolicy: Delete
  forProvider:
    name: Netbird Backend
    accessType: CONFIDENTIAL
    clientId: netbird-backend
    clientSecretSecretRef:
      namespace: netbird
      name: netbird-backend-oidc-credentials
      key: clientSecret
    description: Netbird Backend Client
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: true
    oauth2DeviceAuthorizationGrantEnabled: true
    validRedirectUris:
      - "/*"
    webOrigins:
      - "+"
    realmIdRef:
      name: master
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientServiceAccountRole
metadata:
  name: netbird-backend-view-users
spec:
  forProvider:
    clientIdRef:
      name: builtin-master-realm-management
    realmIdRef:
      name: master
    role: view-users
    serviceAccountUserClientIdRef:
      name: netbird-backend
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: netbird
spec:
  forProvider:
    name: Netbird
    accessType: PUBLIC
    clientId: netbird
    description: Netbird Client
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    oauth2DeviceAuthorizationGrantEnabled: true
    baseUrl: "https://netbird.4546b"
    validRedirectUris:
      - "http://localhost:53000"
      - "https://netbird.4546b/*"
    validPostLogoutRedirectUris:
      - "https://netbird.4546b/*"
    webOrigins:
      - "+"
    realmIdRef:
      name: master
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: netbird-default-scopes
spec:
  forProvider:
    defaultScopes:
      - acr
      - email
      - profile
      - roles
      - web-origins
      - netbird-api
    clientIdRef:
      name: netbird
    realmIdRef:
      name: master
