apiVersion: v1
kind: Secret
metadata:
  name: netbird-backend-oidc-credentials
  namespace: net-system
type: Opaque
stringData:
  clientId: netbird-backend
  clientSecret: {{ randAscii 32 | quote }} 
