apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Release.Name }}-database-secret'
type: kubernetes.io/basic-auth
data:
  username: {{ include "database.username" . }}
  password: {{ include "database.password" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: existing-{{ .Release.Name }}-secrets
type: Opaque
stringData:
  config.yaml: |
    Database:
      Postgres:
        Host: {{ .Release.Name }}-rw.{{ .Release.Namespace }}.svc.cluster.local
        User:
          Username: {{ include "database.username" . }}
          Password: {{ include "database.password" . }}
