apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie
spec:
  secretName: mealie-tls
  privateKey:
    rotationPolicy: Always
  commonName: mealie.wimandnaomishome.com
  dnsNames:
    - mealie.wimandnaomishome.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: cloudflare 
    kind: ClusterIssuer
