apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie 
  namespace: home-automation 
  labels:
    app.kubernetes.io/name: mealie
spec:
  postgresGID: 1000
  instances: 3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  postgresql:
    pg_hba:
      - hostssl all all 10.244.0.0/16 trust
      - hostnossl all all 10.244.0.0/16 trust
  bootstrap:
    initdb:
      database: mealie
      owner: mealie
  storage:
    size: 16Gi
    storageClass: 4546b
