apiVersion: v1	
kind: ConfigMap	
metadata:	
  name: mealie	
  namespace: home-automation	
  labels:	
    app.kubernetes.io/instance: home-automation-mealie	
    app.kubernetes.io/name: mealie	
data:	
  BASE_URL: 'https://mealie.wimandnaomishome.com:443'	
  OIDC_AUTH_ENABLED: 'true'
  OIDC_AUTO_REDIRECT: 'false'
  OIDC_PROVIDER_NAME: 'SSO'
  OIDC_CONFIGURATION_URL: 'http://authorization-keycloak.authorization.svc.cluster.local/realms/master/.well-known/openid-configuration'
  OIDC_USER_GROUP: read
  OIDC_ADMIN_GROUP: admin
  DEFAULT_GROUP: Home	
  MAX_WORKERS: '1'	
  PGID: '1000'	
  PUID: '1000'	
  TZ: Europe/Amsterdam	
  WEB_CONCURRENCY: '1'
  LOG_LEVEL: debug
