apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:	
    app.kubernetes.io/instance: home-automation-mealie	
    app.kubernetes.io/name: mealie	
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-automation-mealie	
      app.kubernetes.io/name: mealie	
  template:
    metadata:
      name: mealie
      labels:	
        app.kubernetes.io/instance: home-automation-mealie	
        app.kubernetes.io/name: mealie	
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.12.0
          env:
            - name: DB_ENGINE 
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-app
                  key: user
            - name: POSTGRES_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mealie-app
                  key: pgpass
            - name: POSTGRES_SERVER 
              value: mealie-rw.home-automation.svc.cluster.local
            - name: POSTGRES_PORT 
              value: "5432"
            - name: POSTGRES_DB 
              valueFrom:
                secretKeyRef:
                  name: mealie-app
                  key: dbname
          envFrom:
            - configMapRef:
                name: mealie
                optional: false
          ports:
            - containerPort: 9000
              name: web
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /app/data
              name: mealie-data
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: / 
              port: 9000 
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
      volumes:
        - name: mealie-data
          emptyDir: {}
