apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: mealie
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: mealie
    envs:
      - config.env
    options:
      disableNameSuffixHash: true
