apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: mealie
spec:
  forProvider:
    name: Mealie
    accessType: PUBLIC
    clientId: mealie
    clientSecretSecretRef:
      namespace: mealie
      name: mealie-oidc-credentials
      key: clientSecret
    description: Mealie Client
    standardFlowEnabled: true
    directAccessGrantsEnabled: false 
    clientAuthenticatorType: client-secret
    oauth2DeviceAuthorizationGrantEnabled: false
    frontchannelLogoutEnabled: true
    implicitFlowEnabled: false
    serviceAccountsEnabled: false
    pkceCodeChallengeMethod: S256
    useRefreshTokens: true
    backchannelLogoutSessionRequired: true
    adminUrl: "https://mealie.united/"
    rootUrl: "https://mealie.united/"
    baseUrl: "https://mealie.united"
    validRedirectUris:
      - "https://mealie.united/login?direct=1"
      - "https://mealie.united/login"
    validPostLogoutRedirectUris:
      - "https://mealie.united/login?direct=1"
      - "https://mealie.united/login"
    webOrigins:
      - "https://mealie.united"
    realmId: 4546b
    realmIdRef:
      name: 4546b
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  name: groups 
spec:
  forProvider:
    name: groups
    description: Add groups to token
    includeInTokenScope: true
    realmId: 4546b
    realmIdRef:
      name: 4546b
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: groups
spec:
  forProvider:
    name: groups
    protocol: openid-connect
    protocolMapper: oidc-group-membership-mapper
    config:
      full.path: "true"
      introspection.token.claim: "true"
      userinfo.token.claim: "true"
      multivalued: "true"
      id.token.claim: "true"
      access.token.claim: "true"
      claim.name: "groups"
    realmId: 4546b
    realmIdRef:
      name: 4546b
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: mealie-default-scopes
spec:
  forProvider:
    defaultScopes:
      - email
      - profile
      - groups
    clientId: mealie
    clientIdRef:
      name: mealie
    realmId: 4546b
    realmIdRef:
      name: 4546b
