---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie
  namespace: home-automation
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgBtLoy5AjQcQgeETU4hC2zaoVF3VwelhyHVLXdRVv8/L+cv/mBbV39ljIpgocS1466KgjPhqTeMnd2biPhZ/M2esHJS4Fop70i+C+PbKnUEDMR01XWcicyasN85YLZ7qJaM9L8DKobr/XS4PnfRzlVf5qg+i1E2K4SyAPu+GvydUsOLRhK7vnebkkHIIbpIjEGw7RPOY6wBW5E+RIF68hhSM9ix20ndgjySgumijuWWLCqFW/LCFEc1yfACSyqyfwukJZOqln9yon9u2psp2ZSOhQt8jmxh7Wxz/wDHuwcZNUZV1dxmTMVHHn5OyyF3xwgJITPOZIvdF7TPppjx95oNw4Fe7kRwGwqGiEOVrW6mxAdxKDvkE0ZLUlhJqbc3KjBbGTJd5T60QssPGi+VYnt4inMgnzfSS/6TzR/ab+RhgroOmWDEGrwe1RERBHjSokCRgbot9y9UeteZTOwVecYLEZ82TLvxwaX65FEQ1gLNPJWj1fxXMbYky5GHfH8tqEiRXHx1GP4sHXiq2aF0SEUWCTck1hkPU3TjDoRmB9bQC5eSJd+SwyY3CFFPiZxLiOU7wtdVJ0chzQo5TtyYBjn7mGSMNcvY230tET2r7iQtQDu+bnwSWYwVmDPl5Vh8bSUDvhtO1lUiWdPBmNjcjjyVDyT4lM/CR3HrNL3UGG5DOXWcT9an6cRpiXxJdDDP69oPSW7G9y0=
    OIDC_CLIENT_SECRET: AgAYemD6I2ecvvjH/9Uk+f3QMZifNmYhufP/+WyyK9BZN5JApNoaUXKk7IS7E+w7kC1Aax5oR811jUNWIK3h/N3TKVWLNxnQavNlaNpJIp+TnQwGb2SQwGSJi3F2X9kjXMBrHVjbC9BjnsUMWvN+H4JC9qp2G/CbevyuKGB4PmL+02/czN2hQD07RdO9L7bdyMdUvfFPeeoJErRZVjwWRJEbVG+HhinLyUvgtZxGZZrRp5NGSXm9ePzPyfvHAYitmo2J3OC7Gik7Geh62K+yXUCKbzRf4u2Qj7h5+MS8j7hMia7aERTdgKAOAzgtsKy8O2ECztzgGk8ZXrKzRJ8LIwMifluV3jrDDD5gNyZ7o+KWOiVlo11TnmGJ7Ct94Ijcd9Bi9aq4Y/Si4g1EOlo9atTd+T3HRZcTpp0IOYhGNn41v1hll6EZRfuQ2AUpAk0zUMEHiGcCWa+qcGrL5MuUfwYPcWAE2F1zYUlX1e61wY6zV/0piWWjDie/zCMSGdUhKiVXRSExot8rWk8m2UgVd9n4O7M376pM3axDRwgE6lFbh86GMayEhO6/HVPzJqFBFbXqVJq4SFDji8Rs4KZ5JtywgBUeb+j+WUTt623Yuyn2rPEBkNY6kQajcHkuGESrw0J5zNBJHH2AfLllCXJYe+1z7ovh9APKgjatl09ThnUkrPAXg6Jwqn9QBK//QbqbEFp8jX9CPoYZb/YJ1gCAy1jbKEpRAo+xjIbB2NDxr5S7Ig==
  template:
    metadata:
      creationTimestamp: null
      name: mealie
      namespace: home-automation
