apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie
  namespace: home-automation
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgBPWaFLzdA0uAwtvIQXLWcV7qWkF2D3DbtbTNfBC33BUa0ruumVOBEFigbmRYNHepvTU6e6QHlAk6lLlGjENuRcYQQX49SAVkG86SdMh0PjZq7XB4xkH0/chVdjxq///OteW0G81kIQe/cDeuxknDfSS6pgJJnO8DG633hJ7RLZvXB2s9jQ2xZAUxvAusqwXDNHmOO1exvVJNfoC3c2l2XTB1RuhcPMRIXYei1hmdg3aV+zy/xzI4a8ettA9uEhk4pwfVxHxN9nzIpcYrNeV5wHu0+rhmWK4Y3cjzt5XqrlHdmXr7BAHhe2zqHAIlHch7GNaTEw7fFz6K6cPJea49PyAQKJVPMQPwcmXwYRzrcVpUpmS8VwUXx2b3zgCsu3SbbGGCzwjddSkDbjWQZvuvNr19J/6T+7bozqwy510Z0UAvkg+FbjCQL5dAF08UuoYt0dZrCUQJp4R9404OLpHlQtfg1Eyui162TBzofe/b1PeLdQCdhN9+8KRMjLUCfPnbXrx4FOaO6diZo5C3waqBSNW8K/bGpIySvOse5wgusz0o7pMHD04jt/j+F0xj9BkhN/O5JIhdaTxF2IGRjzb8Ii3CLfSjZq3VFsE5r5dOgMe4HTur934kcZz51ucQpLlDtgdZ8uB3rov/CPfi8MC3rIZHc90ab2FOPmz2rGegg21d6nXI7YPwBx9soih58FW2pgXO22MNWq
    OIDC_CLIENT_SECRET: AgBUysLy97aI5FQG26jJanHUGQ4UfWdl3FiFvodOBhbTb6yKplHHULxaqIzkwP+TP9Z9daWYb6Ii85PdOAbfl0OXy6yrHkM9ECLg4uDNzuP7u98c0Ay9YS5eVQnvBD5xbRf/od+w9c2UJApaIHuEbFyHYkEBAF37xemRRdfRSdiHT1WvClwak52cwI+rpTGQ/DkTskUQRCr0g4yNJRRFyHT9iNk0LVPipB+gN7AbS+KhOUlDBvw1f0P1qgmsUOdi9SAOlI6zMGBcAwit6xh7lSEkLoU4FXGMe2sDIu2zBrnwyzVcLzhV1sqNRvbgAfYfqP9f1UXMF/9xioFbe8Z/PAK+iGln5Oe718TRJQ2u607kRdjIstHgpZwmPSvf5VxmACSQs7DvwZia6gGDYsqSpxXHmlEWEEROeYtNMfWi7DHWPzEuEQ1MluVyVoTpxhfWSVIjbU2ehvjDfRfSGtuZTv65lc3LOlpME9zMDXAxxXwMQiW048GZKuRqEKYNsEiG75moXiKItwFfGYazivKIA2vPdheGP8AC9bYUVnFTCOiI8vISmdwYm62qqhFA0WISe453LQ4I84oahHqUc/KbvKDqIJOZI1wVoBMuuh87NLeTVcgN0J3qDBJ6+QAnSNrdMN8070Y0HpHQ8uKFgr32c32+0Bfwn6UhaO+UCPXmxGuuZbkSxlNc9Y6PTcpK3eDWV2dHFbzQfmDQz3L2rNOwcXbLa9gmeDku+fyDTIgUczngqA==
  template:
    metadata:
      name: mealie
      namespace: home-automation
    type: Opaque
