apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-oidc-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgA3LAqHSGZfQ1H4kaZ2WptWFSVufrcTTBO1/6aPoix21EZUtHQmeGL2wLN9djqT1KPjclYgiuwJBenuuFHgc9SitZjx/ohNvmAhcOrFiClBYa9572hbAMAu+JakrfroRXDnVPXLI6HZGVk12DRJfH687iNu8kfQzbp7zvuCJb8rbyq8HTyUvVfVW3ttc77cLv0yafoR/Wx7PqvNljfFdgqsgBokuV02Cs5pIeKulSNvQew0kyCLM8bWwscSJonpWu3XFO4llRnycTwFUcJr7EnO/xfOQFaSYVa/HuhCVf78/E0vxlJev6Jd3Zh0BydvidCop4CnxGtOUOT5T0TYPZuLYUVpkN7QSKIYAurqyjslkOLMIEPbYIOfog9sQo81vAQ9W3zyNFljipC9xoLB+b+NX0dhq82h1d9JVyET0QlryPyBoJv/DeZpkZXHHgz+T3epUKeGFrz/NFX0TPPQjKuD04VJqrsjR/5NXXYZ8Tp2FssVlUDtcHMW4WHTs48KfAu+ypqvUdg44IUiAx+UJR2ksteMbK80zNvz3POjeyihLRE0E5aoeTcu3L/QmmYCcG+1Ta42lVCNwTntyobLG41W06i4IfHXpoBUM0Ayz7J3697sE+wlr5I9cP5hy8R72Y5GLUgnKRM5rIJXhSkliWuhks6nBmPYXEeL9P+uGYHmGI++WsQ2mRVpG5Uoml1JVLHW4gw6C+T4cKHtGQfbUnhSQ9Izv1/14U1U+7/avphiaQ==
  template:
    metadata:
      name: mealie-oidc-credentials
      namespace: home-automation
