apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.united
  name: home-automation-emqx-mqtt
  namespace: home-automation
spec:
  loadBalancerIP: 10.0.0.243
  ports:
    - name: mqttssl
      port: 8883
      protocol: TCP
      targetPort: mqttssl
  selector:
    app.kubernetes.io/instance: home-automation-emqx
    app.kubernetes.io/name: emqx
  type: LoadBalancer
