cert-manager:
  installCRDs: true

  namespace: infra-system

  global:
    commonLabels:
      argocd.argoproj.io/instance: infra-system-cert-manager

trust-manager:
  namespace: infra-system

  commonLabels:
    argocd.argoproj.io/instance: infra-system-cert-manager
  
  app:
    trust:
      namespace: infra-system
