keycloak:
  production: true
  proxy: edge
  metrics:
    enabled: true
  postgresql:
    enabled: false
  externalDatabase:
    host: keycloak-rw.authorization.svc.cluster.local
    existingSecret: keycloak-app
    existingSecretPortKey: port
    existingSecretUserKey: user 
    existingSecretDatabaseKey: dbname
    existingSecretPasswordKey: password
  auth:
    existingSecret: keycloak-initial-admin-creds
    passwordSecretKey: password
  ingress:
    enabled: true
    hostname: keycloak.4546b
    path: /
    tls: true
