prometheus:
  server:
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    podAntiAffinity: soft
    statefulSet:
      enabled: true
    persistentVolume:
      enabled: true
      storageClass: 4546b
    replicaCount: 3
    retention: "7d"
    retentionSie: "8GB"
     
  kube-state-metrics:
    enabled: true
    global:
      replicas: 3
    startupProbe:
      enabled: true

  prometheus-node-exporter:
    enabled: true
    hostPID: false
    hostProcFsMount: 
      mountPropagation: HostToContainer
    hostSysFsMount:
      mountPropagation: HostToContainer

  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

