zitadel:
  zitadel:
    masterkeySecretName: zitadel-master-key
    configmapConfig:
      TLS:
        Enabled: false
      Database:
        Postgres:
          Host: zitadel-rw.infra-system.svc.cluster.local
          Port: 5432
          Database: zitadel
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
          User:
            Username: zitadel
            SSL:
              Mode: disable
          Admin:
            Username: zitadel
            SSL:
              Mode: disable


    configSecretName: existing-zitadel-secrets
    configSecretKey: config.yaml
