linkerd-control-plane:
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBjzCCATSgAwIBAgIRAKICvHWiukZ89/RNRWmi608wCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjQwNTE4MDUx
    MDM0WhcNMjkwNTE3MDUxMDM0WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
    c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHo+VD3PFhNXhEYj
    kMyOBzIHZEnZzdYBMg+isCdp5IvIypW9Q3MCIvwczMtth2tuDvQuktCp66ZvIfIt
    Zz/a1UejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
    A1UdDgQWBBSC2SSs9m0KQCTi0vrzUeHHHtt4ODAKBggqhkjOPQQDAgNJADBGAiEA
    357y18SEJ9bh0FR7jBTE50LACImbCiNMlR91SsQNPrMCIQCXj98nliCFoxkTO96c
    MQ5Yy6EFzbPzu1+TwJrSfC+RvA==
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
