apiVersion: v2
name: rook-ceph
version: &version v1.19.2
dependencies:
  - name: rook-ceph-cluster
    version: *version 
    repository: https://charts.rook.io/release
    enabled: false
  - name: rook-ceph
    version: *version 
    repository: https://charts.rook.io/release
    enabled: false

