apiVersion: v2
name: rook-ceph
version: &version v1.19.3
dependencies:
  - name: rook-ceph-cluster
    version: *version 
    repository: https://charts.rook.io/release
  - name: rook-ceph
    version: *version 
    repository: https://charts.rook.io/release

