rook-ceph-cluster:
  operatorNamespace: infra-system

  cephClusterSpec:
    mon:
      count: 1

    mgr:
      count: 1

    crashCollector:
      disable: true

    logCollector:
      enabled: false

  cephFileSystems:
    - name: ceph-filesystem
      spec:
        metadataServer:
          activeStandby: false
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
