apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: gitea
  namespace: infra-system
spec:
  clientId: gitea
  secret: $gitea-oauth2-credentials:secret
  realmRef:
    kind: ClusterKeycloakRealm
    name: internal
  webUrl: https://gitea.united
