apiVersion: v1
kind: Namespace
metadata:
  name: csi-driver-nfs
  labels:
    kubernetes.io/metadata.name: csi-driver-nfs
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
