apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: 4546b
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.32 
  share: /mnt/forty-five-forty-six-b/cluster 
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
allowVolumeExpansion: true
