apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dnsmasq  
  namespace: net-system 
  labels:
    app.kubernetes.io/name: pihole
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
    server=/.united/10.0.0.240
