apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: net-system
spec:
  refreshInterval: "0"
  target:
    name: pihole-password
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password-generator
