apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: net-system
spec:
  encryptedData:
    password: AgArsqlHXF7hSE8Srcw0k/Af+jLfvw2DGpFlX9sWkmca39F0IENtcK1BahQFL9mjl9DRIpyLJin2fX2EoNTdzj53V5y854qUJuN5QnCzZzfhJfr8h1iH3FoXpCgtZbabx763dxOUNgqOfMRqF9pXXQnSid/ULWrWfXknZuCVqZLInVxS6Dycg8p4hBtc1DuDB/lITDowp8KAXqj5dSrYR3BLKATi+wt+JKeKHWjWqMKZK+Uqc4vDk9xJgf5YchVCe86D98PvMjtkrqIMzIOoNLvF1O/F8xS/l9QPVR8OV3aqP9YsDhc7esyv0pib1hXkeU5t38IT4O4TToVfYoL142hqp8qW3TQ5wu9yiwJd9kaZmjgu7AEZBa/iB3IzR1U28hGRPl8wbELTArqNsoeSQB4R+4ZumOFqpS/G7YFQ7VDSs2YkLR/X8Umvv5bHBaHpfr0wS23Vw7iibpQjy77U9KlNNKWL6gIEa7sUnBOV7Lzz4Ol+C056gB4eIODaskicqHq/Ylo+rrhRTB4fiCF+llt/JrCqR0XxijeLS9MCOUMiXtY6HIfH4XVQkbN00to6tIwY6pKIR1ISiY1cbNzU6DtRHWHOHFKpBULxnx4IeXiQcMYb/cuxdnjVMAQ76yR3GNGNIyKx60fKmK62bH8XYT+cxndpqmdCxIByt8hYEVK+txrhcYA0px84u7VvH9Qc7nE7UlDf0iS8zpmrcUiNa2dKhFBoab0o9gdOuh3cQXQvie99/XTOmeaAj+lywg==
  template:
    metadata:
      name: pihole-password
      namespace: net-system
