apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-initial-admin-creds
  namespace: authorization
spec:
  encryptedData:
    password: AgAxVYelo0WBpI1BsAxo3WTrPvcq5NROAUS2rKGjkX8MFZkcocRx8f9qisf5CvN1bTBa81e0xzpCLP+qbQyHpepboF0IOhI/X/y33QBZUd6hbNzMLZkZLfFE3ScHUGXR8BAAtWvK/Zx5TrM9A+fz3hXu0WqGpJYDcmRsd5EeaybLDgC4vgGV2+XalqiUfpeTAemNmqtpOYrJ/ejjW9iLm/cowbd8la3ZErYF+rGkWVIrJyrV/iTNt8+7F1OX0sPJh4XjL97h/iTTF1JgGZOxFvQ3AHGmQMGljZ3+hVDM6u6aXrh4DI8GQcLrqbU6dG8ZLKl9wt++AaBtJoWL+jGss04+5pV32c4GRJSIGebWcKhNo2Ab0wf/1foHxgEWwuNBIzKys+Cn6GpdEDIRzU/VG4MJFKKuDKuaF7J5+g+YkkeUdHJJwgL7xuzn+GKKDb97OirA7p9nSZ+RabiTOq18TMnevc0PCMQGDmckNrBikrgziq3fc3iPvaij87mRP1rgt78rT6toFhUZVMaPhDhyb93Wyo9yvQUliCAs6G1TqtQBkzKw9QNeDLFg65uCK+q03FTv6wgQiK+aVrooh663NAnB++bromm+vUoco4R/+e1rHFdFnotrScEvSMHv2GisnY2h18KXpVcOrzkleslaD8nYczGKn5GWzNri7QWPyyc5kn6zs5euA8tEMVBbFNcPydUW2ycQ++GkQVbbap1WWQBEecwnRgksGamp5857NU2BQSndlEi4C0xmJkllPQ==
  template:
    metadata:
      name: keycloak-initial-admin-creds
      namespace: authorization
