apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-initial-admin-creds
  namespace: authorization
spec:
  encryptedData:
    password: AgCZIjYmcYgaGRPkpY4bbvMgsj4R9Z5ZGjpxSDi0cjDOXwnXZhgjd8ghce8+c/TqYt7Rly8ENMBeeg5OoAVKi5q5b+bPuKUSjwpQ0BTinU1yW09opErrBmRseJH5+Ja56g/wz07+D9vXf+R4Y4B9r8rIZXgBo6ZhKBJmY0BlwM1PMcwr31onqoFaP+6LMOuWCw7rrhtjXtHmwsO11utGg0UQ+vzM7Ydm/oICLyJor48PjzHnCKyXnzdaB/RFmMNRJMKyPt6JLe+FYSKud0DZhANmdQp2+1W1doq48glzHs5qTzSFn7tUCXjnUItcOL/+dYkjAkDqP/wxCFGhmYHrgSLaS6IXgECIVxxCn6Nhy2fcxcFvQZooZTsVMA7ZKbQp+V8w6jHdB/WziHR+F/XqeGwcLNNdRJjpbrD/Xn4SQB5zBFNszJXzP2E/FKKTXAc1DoTH2HF03WGWUuCr0mr54BKfjv8gHSs7wQ7kAO6JLA2PxWVKOxmG96TZzUrurK4Oz7EhcWVRZZr1NVXoKHQhSfRww3FNmG8ZzXArgIrhQuuQXNlqQ3RXFy0dAfcSRzLtiy7PQGPoeSyWR76V0oxbe3ADdoI/WCeBJvsyjypcs7C66q+2NvfIOv/n1mWkbk6VJlWEhCe7hJzNo67CV/XLSuQinxhjt5qQw1aIxGl9F4XAXP/XMgx16bCCNWnCJgEANDehMSZ58SeBksTpfDO23vGJ0Z6GtJFgnYK+mD+G9ZZRicDT1UiLxSDiob4tcA==
  template:
    metadata:
      name: keycloak-initial-admin-creds
      namespace: authorization
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane
spec:
  encryptedData:
    credentials: AgAe86DydVu3cm2WFGdUcWGHP+R5TjzlFAOt0j9pzCQjoClnQbhTYpYxO1vIiDoMjqt0nh4FsQVrz56RHBtDjSODrv28OvAWmPT/N1XLpqiMW7r1xSdpRargyzUWUhDgSnduGDFAteUC36twZAt5ZJdmlz5vFhYHfqKF/o78OFHvP2XIpN0aHDCcCWmZvbUC9U+1J1oIEmXC+IGsSlNuYCSnsw2J4iPBCLtzyKMogW9BNUw4O/Ic7GdM2bJt3pjrb7wRURj6U8ofpYyeV3ZKaaJ0t4KonIpkNg9hq54NoWLsDFfw0jcb63+gePbuYiCz8J5R3TZuEKLj8eOm4xNnwSDuFdbitApBn42kwi/Rppnvic2be24JYfFiskL7GBf8cFeiGiz+C5+J5f9j45N801T5GSmaFA30K1Tj2A8HfHOA2XsUE0Y3dMQv8dJxqxqtTnTESj1T43V29svblLgg34MOP8EyQG0fA8IfLRDH/hPC5YRmQYTdQzFbh1qUjuPuu2SMGHzIKm14Wlh3bSJjTfq5+XYtrl/F4cEv7Ii0Ujcfc3XUmmOJaztU+4ZmyDIRNSFmBjFMsyj3JO6bVbrKK5jqLvgfMNhJiZXlodKXbfHRj4pOqCgippqkWpGjmW1007FOIbrcKZKUKzDSSqj0OKkhIvim2TX+YoGhcTiTtQlYnYVXYk3fMJue8hF2oEvTLhfRYnHvWaycg6piiJpJqjKdHTzFO9+jGRuAUpYglq4lDAcWxxDitzBUClb4IbbcFoOrCg4Yr8OcF5TcugdDbljwoSDCYqjq4/i4bePfv5lwE/AX97+eCVT/6swdJkiXE+3cYPm94qYLJ6PamR8nz7/8NaoO8ADl5TL5k5iw8yM4ebu32jPmlODkXaE66qym6oN2FRQuornRVS5HIGyC5+jNL0C63uqZWVGSDXyIFLK7bQ5QMjzA1m+g2ZydgAgz
  template:
    metadata:
      labels:
        type: provider-credentials
      name: keycloak-credentials
      namespace: crossplane
    type: Opaque
