{{- $password := randAscii 32 -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin-creds
  namespace: authorization
type: Opaque
data:
  password: {{ $password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: crossplane
  labels:
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id": "admin-cli",
      "url": "http://authorization-keycloak.authorization.svc.cluster.local/",
      "username": "admin",
      "password": {{ $password | quote }}
    }
