apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: bob
spec:
  forProvider:
    enabled: true
    email: bob@domain.com
    firstName: Bob
    lastName: Bobson
    username: bob
    realmId: 4546b
    realmIdRef:
      name: 4546b 
