name: Renovate

permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: '0/15 * * * *'
  push:
    branches:
      - main

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.3
        with:
          configurationFile: .github/renovate-config.js 
          token: ${{ secrets.RENOVATE_TOKEN }}
